on:
  push:
    branches:
      - main

jobs:
  build-completion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Setup Rye
        run: curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
      - run: echo "$HOME/.rye/shims" >> $GITHUB_PATH
      - run: rye config --set-bool behavior.use-uv=true
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      - run: rye sync
      - run: rye run aws
